config/routes.rb
Rails.application.routes.draw do
  get 'accounts/index'
  get 'accounts/show'
  get 'accounts/new'
  get 'accounts/edit'
  devise_for :users
  root 'books#index'

  get '/about', to: 'static_pages#about'
  resources :books
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :account
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update]
  def index
    @books = current_user.books
  end

  def show
  end

  def new
    @books = Book.new
  end

  def edit
  end

  def create
    @books = current_user.books.new(book_params)
    if @books.save
      redirect_to accounts_path
    else
      render :new
    end
  end

  def update
    if @books.update(book_params)
      redirect_to books_path
    else
      render :new
    end
  end

  def destroy
    @book.destroy
  end

  private

  def set_account
    @account = current_user.accounts.find(params[:id])
  end

  def book_params
    params.require(:account).permit(:first_name, :last_name, :book)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # before_action :set_account, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end
end

private

  def book_params
    params.require(:book).permit(:title, :author, :body, :keywords)
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/accounts/edit.html.erb
<h1>Accounts#edit</h1>
<p>Find me in app/views/accounts/edit.html.erb</p>

app/views/accounts/index.html.erb
<h1>Accounts#index</h1>
<p>Find me in app/views/accounts/index.html.erb</p>

app/views/accounts/new.html.erb
<h1>Accounts#new</h1>
<p>Find me in app/views/accounts/new.html.erb</p>

app/views/accounts/show.html.erb
<h1>Accounts#show</h1>
<p>Find me in app/views/accounts/show.html.erb</p>

app/views/books/edit.html.erb
<h1>Edit Page</h1>
<%= form_for @book do |f| %>
  <%= f.label :title %> 
  <%= f.text_field :title, autofocus: true %> <br><br>

  <%= f.label :author %>
  <%= f.text_field :author %><br><br>

  <%= f.label :body %>
<section id="bigtext">  <%= f.text_area :body %></section><br><br>

  <%= f.label :keywords %>
  <%= f.text_field :keywords, class: "big_field" %><br><br>

  <%= f.submit %>
<% end %>

app/views/books/index.html.erb
<%= button_to  "Log Out", destroy_user_session_path, method: :delete %> </h2>
<h2>Welcome <%= current_user.first_name%>!</h2>
<p id="notice"><%= notice %></p>
<h1 class= "ui header"> Books </h1>
<table class="ui striped table">
<thead>
<tr class="center aligned">
<p><%= link_to 'New Book', new_book_path %></p>
</thead>
<tbody>
<% @books.each do |book| %>
  <tr class="center aligned">
  <h2><%= book.title %></h2>
  <div class="ui three item">
  <button class="ui secondary basic button"><%= link_to 'Show Book', book_path(book) %></button>
  <button class="ui secondary basic button"><%= link_to 'Edit Book', edit_book_path(book) %></button>
  <button class="ui secondary basic button"><%= link_to 'Burn Book', book, method: :delete %></button>
  </div>
</tbody></table>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= form_for @book do |f| %>
  <div><%= f.label :title %>
  <%= f.text_field :title, autofocus: true %></div>

  <div><%= f.label :author %>
  <%= f.text_field :author %></div>

  <div><%= f.label :body %>
 <section class="bigtext"> <%= f.text_area :body %></section></div>

  <div><%= f.label :keywords %>
  <%= f.text_field :keywords %></div>

  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h4><%= @book.author %></h4>
<p><%= simple_format(@book.body) %></p>
 <%= @book.keywords %>
<button class="ui secondary basic button"><%= link_to  "Back", books_path %></button>
<button class="ui secondary basic button"><%= link_to 'Edit Book', edit_book_path(@book) %></button>

app/views/layouts/_navbar.html.erb
<button class="ui secondary basic button"><%= link_to 'Home', root_path %></button>
<button class="ui secondary basic button"><%= link_to 'About', about_path %></button>
<button class="ui secondary basic button"><%= link_to 'Books', books_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Doctors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/navbar' %>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>The Book Doctors' Mission</h1>
<p>Books are good for what ails us, giving us help to overcome challenges, heal heartaches, energize passions, or even therapeutically step out of our own often myopic lives to let us experience something different. </p>
<p>Once a book doctor finds out what is ailing his or her patient, the challenge is to find the right book to prescribe. That's where the Book Doctors website comes in. Here all the successful book doctors of the world can come to share their go-to book prescriptions for the variety of ailments they routinely see. Then, aspiring book doctors can come to access the wealth of literary remedies prescribed by the best book doctors around!</p>
<p>So come explore the prescriptions here and find the remedies for what ails your friends or even yourself!</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>